logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard
  - code: YN0006
    level: discard
  - code: YN0013
    level: discard
  - code: YN0062
    level: discard
  - code: YN0063
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
