name: Master Cache

on:
  push:
    branches: master

jobs:
  Test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/init
        with:
          node-version: ${{ matrix.node-version }}
